from typing import Callable

help_app_name = "Aoco"
help_app_description = "Advent of Code helper cli application"
help_init_command_description = "initialize the configuration for a new AOC project"
init_selection_year = "For what year are you challenging?"
init_selection_session = "Please provide your Advent of Code session token"
day_selection_select_day = "Select day"
day_selection_day: Callable[[str], str] = lambda day: f"Day {day}"
run_phase_should_continue = "Continue to production data?"
run_phase_should_submit = "Record answer?"
run_phase_already_submitted = "Already submitted!"
run_phase_well_done = "You completed this day! Well done!"
run_phase_answer: Callable[[str], str] = lambda answer: f"result: {answer}"
run_phase_header_prefix = "RUNNING"
run_phase_header: Callable[[str, str], str] = lambda part, day: f"day {day} | part {part}"
run_phase_header_suffix = "(test)"
